APP:
  ENV:  "development"
  PORT: ":1112"
  DATABASE_NAME: "cegxbczruu"
  DATABASE_USERNAME: "cegxbczruu"
  DATABASE_PASSWORD: "Package@123#"
  DATABASE_PORT: "3306"
  DATABASE_SERVER_HOST: "139.59.69.8"
  USER_CONTEXT_KEY: "usercontextkey"
  JWT_SECRET_KEY: "secret"