// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	Categoryid int    `json:"Categoryid"`
	Name       string `json:"Name"`
	Type       int    `json:"Type"`
	SortOrder  int    `json:"SortOrder"`
	Status     string `json:"Status"`
}

type LocationInfo struct {
	Locationid   int    `json:"Locationid"`
	LocationName string `json:"LocationName"`
	Status       string `json:"status"`
	Createdby    int    `json:"createdby"`
}

type Module struct {
	ModuleID   int    `json:"ModuleId"`
	CategoryID int    `json:"CategoryId"`
	Name       string `json:"Name"`
	Content    string `json:"Content"`
	ImageURL   string `json:"ImageUrl"`
	LogoURL    string `json:"LogoUrl"`
}

type Package struct {
	ModuleID       int    `json:"ModuleId"`
	Modulename     string `json:"Modulename"`
	Name           string `json:"Name"`
	PackageID      int    `json:"PackageId"`
	Status         string `json:"Status"`
	PackageAmount  string `json:"PackageAmount"`
	PaymentMode    string `json:"PaymentMode"`
	PackageContent string `json:"PackageContent"`
	PackageIcon    string `json:"PackageIcon"`
}

type Promotion struct {
	Promotionid     int     `json:"Promotionid"`
	Promotiontypeid int     `json:"Promotiontypeid"`
	Promotionname   *string `json:"Promotionname"`
	Tenantid        int     `json:"Tenantid"`
	Tenantame       *string `json:"Tenantame"`
	Promocode       *string `json:"Promocode"`
	Promoterms      *string `json:"Promoterms"`
	Promovalue      *string `json:"Promovalue"`
	Promotag        *string `json:"Promotag"`
	Promotype       *string `json:"Promotype"`
	Startdate       *string `json:"Startdate"`
	Enddate         *string `json:"Enddate"`
	Status          *string `json:"Status"`
}

type Sparkle struct {
	Category    []*Category    `json:"category"`
	Subcategory []*SubCategory `json:"subcategory"`
	Package     []*Package     `json:"package"`
}

type SubCategory struct {
	CategoryID    int    `json:"CategoryId"`
	SubCategoryID int    `json:"SubCategoryId"`
	Name          string `json:"Name"`
	Type          int    `json:"Type"`
	SortOrder     int    `json:"SortOrder"`
	Status        string `json:"Status"`
	Icon          string `json:"Icon"`
}

type TenantAddress struct {
	Address     string `json:"Address"`
	Suburb      string `json:"Suburb"`
	State       string `json:"State"`
	Zip         string `json:"Zip"`
	Countrycode string `json:"Countrycode"`
	Latitude    string `json:"Latitude"`
	Longitude   string `json:"Longitude"`
	TimeZone    string `json:"TimeZone"`
	Opentime    string `json:"Opentime"`
	Closetime   string `json:"Closetime"`
}

type TenantData struct {
	TenantID   int    `json:"TenantId"`
	TenantName string `json:"TenantName"`
	ModuleID   int    `json:"ModuleId"`
	ModuleName string `json:"ModuleName"`
}

type TenantDetails struct {
	Name          string `json:"Name"`
	Regno         string `json:"Regno"`
	Email         string `json:"Email"`
	Mobile        string `json:"Mobile"`
	CategoryID    int    `json:"CategoryId"`
	SubCategoryID int    `json:"SubCategoryId"`
	Type          int    `json:"Type"`
}

type Business struct {
	Businessupdate *Businessupdatedata `json:"businessupdate"`
	Socialadd      []*Socialadddata    `json:"socialadd"`
	Socialupdate   []*Socialupdatedata `json:"socialupdate"`
}

type Businessdata struct {
	Status  bool   `json:"status"`
	Code    int    `json:"code"`
	Message string `json:"message"`
	Updated int    `json:"updated"`
}

type Businessupdatedata struct {
	Tenantid    int     `json:"tenantid"`
	Brandname   *string `json:"brandname"`
	About       *string `json:"about"`
	Cod         *int    `json:"cod"`
	Digital     *int    `json:"digital"`
	Tenantaccid *int    `json:"tenantaccid"`
}

type Chargetype struct {
	Chargeid   int     `json:"Chargeid"`
	Chargename string  `json:"Chargename"`
	Status     *string `json:"Status"`
}

type Chargetypedata struct {
	Status  bool          `json:"status"`
	Code    int           `json:"code"`
	Message string        `json:"message"`
	Types   []*Chargetype `json:"types"`
}

type Data struct {
	Tenantinfo          *TenantDetails `json:"tenantinfo"`
	Tenantlocation      *TenantAddress `json:"tenantlocation"`
	Subscriptiondetails *Subscription  `json:"subscriptiondetails"`
}

type GetBusinessdata struct {
	Status       bool   `json:"status"`
	Code         int    `json:"code"`
	Message      string `json:"message"`
	Businessinfo *Info  `json:"businessinfo"`
}

type Getalllocations struct {
	Status    bool              `json:"status"`
	Code      int               `json:"code"`
	Message   string            `json:"message"`
	Locations []*Locationgetall `json:"locations"`
}

type Getpromotiondata struct {
	Status     bool         `json:"status"`
	Code       int          `json:"code"`
	Message    string       `json:"message"`
	Promotions []*Promotion `json:"promotions"`
}

type Info struct {
	Tenantid    int           `json:"tenantid"`
	Brandname   *string       `json:"brandname"`
	About       *string       `json:"about"`
	Cod         *int          `json:"cod"`
	Digital     *int          `json:"digital"`
	Tenantaccid *int          `json:"tenantaccid"`
	Social      []*Socialinfo `json:"social"`
}

type Location struct {
	TenantID     int    `json:"TenantId"`
	LocationName string `json:"LocationName"`
	Email        string `json:"Email"`
	Contact      string `json:"Contact"`
	Address      string `json:"Address"`
	Suburb       string `json:"Suburb"`
	State        string `json:"State"`
	Zip          string `json:"Zip"`
	Countrycode  string `json:"Countrycode"`
	Latitude     string `json:"Latitude"`
	Longitude    string `json:"Longitude"`
	Openingtime  string `json:"Openingtime"`
	Closingtime  string `json:"Closingtime"`
}

type Locationdata struct {
	Status       bool          `json:"status"`
	Code         int           `json:"code"`
	Message      string        `json:"message"`
	Locationinfo *LocationInfo `json:"locationinfo"`
}

type Locationgetall struct {
	Locationid   int           `json:"locationid"`
	LocationName string        `json:"locationName"`
	Tenantid     int           `json:"tenantid"`
	Email        *string       `json:"email"`
	Contact      *string       `json:"contact"`
	Address      string        `json:"address"`
	Suburb       string        `json:"suburb"`
	State        string        `json:"state"`
	Postcode     string        `json:"postcode"`
	Countycode   string        `json:"countycode"`
	Latitude     string        `json:"latitude"`
	Longitude    string        `json:"longitude"`
	Openingtime  string        `json:"openingtime"`
	Closingtime  string        `json:"closingtime"`
	Status       string        `json:"status"`
	Createdby    int           `json:"createdby"`
	Tenantusers  []*Usertenant `json:"tenantusers"`
}

type Promoinput struct {
	Promotiontypeid int     `json:"Promotiontypeid"`
	Promotionname   *string `json:"Promotionname"`
	Tenantid        int     `json:"Tenantid"`
	Promocode       *string `json:"Promocode"`
	Promoterms      *string `json:"Promoterms"`
	Promovalue      *string `json:"Promovalue"`
	Startdate       *string `json:"Startdate"`
	Enddate         *string `json:"Enddate"`
}

type Promotioncreateddata struct {
	Status  bool   `json:"status"`
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Promotypesdata struct {
	Status  bool        `json:"status"`
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Types   []*Typedata `json:"types"`
}

type Socialadddata struct {
	Socialprofile *string `json:"socialprofile"`
	Sociallink    *string `json:"sociallink"`
	Socialicon    *string `json:"socialicon"`
}

type Socialinfo struct {
	Socialid      *int    `json:"socialid"`
	Socialprofile *string `json:"socialprofile"`
	Sociallink    *string `json:"sociallink"`
	Socialicon    *string `json:"socialicon"`
}

type Socialupdatedata struct {
	Socialid      *int    `json:"socialid"`
	Socialprofile *string `json:"socialprofile"`
	Sociallink    *string `json:"sociallink"`
	Socialicon    *string `json:"socialicon"`
}

type SubscribedData struct {
	Status  bool        `json:"status"`
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Info    *TenantData `json:"info"`
}

type Subscription struct {
	TransactionDate string `json:"TransactionDate"`
	PackageID       []int  `json:"PackageId"`
	ModuleID        int    `json:"ModuleId"`
	CurrencyID      int    `json:"CurrencyId"`
	CurrencyCode    string `json:"CurrencyCode"`
	Price           string `json:"Price"`
	TaxID           int    `json:"TaxId"`
	Quantity        int    `json:"Quantity"`
	TaxAmount       string `json:"TaxAmount"`
	TotalAmount     string `json:"TotalAmount"`
	PaymentStatus   int    `json:"PaymentStatus"`
	PaymentID       *int   `json:"PaymentId"`
}

type Tenantupdatedata struct {
	Status  bool   `json:"status"`
	Code    int    `json:"code"`
	Message string `json:"message"`
	Updated int    `json:"updated"`
}

type Tenantuser struct {
	TenantID   int    `json:"TenantId"`
	Firstname  string `json:"firstname"`
	Lastname   string `json:"lastname"`
	Password   string `json:"password"`
	Mobile     string `json:"mobile"`
	Email      string `json:"email"`
	Locationid int    `json:"locationid"`
	Roleid     int    `json:"roleid"`
}

type Tenantuserdata struct {
	Status     bool   `json:"status"`
	Code       int    `json:"code"`
	Message    string `json:"message"`
	Tenantuser *User  `json:"tenantuser"`
}

type Typedata struct {
	Promotiontypeid int     `json:"Promotiontypeid"`
	Typename        *string `json:"Typename"`
	Tag             *string `json:"Tag"`
}

type Updatetenant struct {
	Userid     int    `json:"userid"`
	Tenantid   int    `json:"tenantid"`
	Firstname  string `json:"firstname"`
	Lastname   string `json:"lastname"`
	Mobile     string `json:"mobile"`
	Email      string `json:"email"`
	Locationid int    `json:"locationid"`
}

type User struct {
	Userid int `json:"userid"`
}

type Userfromtenant struct {
	UserID       int    `json:"userId"`
	Locationid   int    `json:"locationid"`
	LocationName string `json:"locationName"`
	Tenantid     int    `json:"tenantid"`
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	Mobile       string `json:"mobile"`
	Email        string `json:"email"`
	Created      string `json:"created"`
	Status       string `json:"status"`
}

type Usersdata struct {
	Status  bool              `json:"status"`
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Users   []*Userfromtenant `json:"users"`
}

type Usertenant struct {
	Userid         int    `json:"userid"`
	Firstname      string `json:"firstname"`
	Lastname       string `json:"lastname"`
	Mobile         string `json:"mobile"`
	Email          string `json:"email"`
	Userlocationid int    `json:"Userlocationid"`
}
